# permissions for end users to edit openstackprovisionservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackprovisionserver-editor-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackprovisionservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackprovisionservers/status
  verbs:
  - get
