# permissions for end users to view openstackvmsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackvmset-viewer-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackvmsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackvmsets/status
  verbs:
  - get
