# permissions for end users to view openstacknets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstacknet-viewer-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstacknets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstacknets/status
  verbs:
  - get
