# permissions for end users to edit openstacknetconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstacknetconfig-editor-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstacknetconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstacknetconfigs/status
  verbs:
  - get
