# permissions for end users to view openstackconfigversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackconfigversion-viewer-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackconfigversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackconfigversions/status
  verbs:
  - get
