# permissions for end users to edit openstacktvmsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackvmset-editor-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackvmsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackvmsets/status
  verbs:
  - get
