# permissions for end users to view openstackcontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackcontrolplane-viewer-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackcontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackcontrolplanes/status
  verbs:
  - get
