# permissions for end users to edit openstackconfigversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackconfigversion-editor-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackconfigversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackconfigversions/status
  verbs:
  - get
