# permissions for end users to view openstacknetattachments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstacknetattachment-viewer-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstacknetattachments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstacknetattachments/status
  verbs:
  - get
