# permissions for end users to edit openstackconfiggenerators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackconfiggenerator-editor-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackconfiggenerators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackconfiggenerators/status
  verbs:
  - get
