# permissions for end users to view provisionservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackprovisionserver-viewer-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackprovisionservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackprovisionservers/status
  verbs:
  - get
