# permissions for end users to edit openstackcontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackcontrolplane-editor-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackcontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackcontrolplanes/status
  verbs:
  - get
