# permissions for end users to view openstackconfiggenerators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackconfiggenerator-viewer-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackconfiggenerators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackconfiggenerators/status
  verbs:
  - get
