apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: overcloud
  namespace: openstack
spec:
  gitSecret: git-secret
  openStackClientImageURL: registry.redhat.io/rhosp-rhel8/openstack-tripleoclient:16.2
  openStackClientNetworks:
    - ctlplane
    - external
  openStackClientStorageClass: host-nfs-storageclass
  physNetworks:
    - name: datacentre
      macPrefix: fa:16:3a
    - name: datacentre2
      macPrefix: fa:16:3b
  virtualMachineRoles:
    controller:
      roleName: Controller
      roleCount: 0
      cores: 2
      memory: 20
      diskSize: 50
      storageClass: host-nfs-storageclass
      baseImageVolumeName: openstack-base-img
      ctlplaneInterface: enp2s0 #defaults to enp2s0
      networks:
      - ctlplane
      - external
      - internal_api
      - tenant
      - storage
      - storage_mgmt
