apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackPlaybookGenerator
metadata:
  name: default
spec:
  imageURL: quay.io/openstack-k8s-operators/tripleo-deploy:16.2_20210309.1
  gitSecret: git-secret
  heatEnvConfigMap: tripleo-deploy-config-custom
  tarballConfigMap: tripleo-tarball-config
