apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackNet
metadata:
  name: storagemgmt
spec:
  allocationEnd: 172.19.0.250
  allocationStart: 172.19.0.10
  attachConfiguration: br-osp
  cidr: 172.19.0.0/24
  mtu: 1350
  name: StorageMgmt
  nameLower: storage_mgmt
  vip: true
  vlan: 40
