apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackNet
metadata:
  name: internalapi
spec:
  allocationEnd: 172.17.0.250
  allocationStart: 172.17.0.10
  attachConfiguration: br-osp
  cidr: 172.17.0.0/24
  mtu: 1350
  name: InternalApi
  nameLower: internal_api
  vip: true
  vlan: 20
