apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackNet
metadata:
  name: external
spec:
  allocationEnd: 10.0.0.250
  allocationStart: 10.0.0.10
  attachConfiguration: br-ex
  cidr: 10.0.0.0/24
  gateway: 10.0.0.1
  mtu: 1500
  name: External
  nameLower: external
  vip: true
