apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackClient
metadata:
  name: openstackclient
  namespace: openstack
spec:
  deploymentSSHSecret: osp-controlplane-ssh-keys
  networks:
    - ctlplane
  storageClass: host-nfs-storageclass
