apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: overcloud
  namespace: openstack
spec:
  openStackClientImageURL: registry.redhat.io/rhosp-rhel8/openstack-tripleoclient:16.2.0
  openStackClientNetworks:
    - ctlplane
    - external
  openStackClientStorageClass: host-nfs-storageclass
  virtualMachineRoles:
    controller:
      roleName: Controller
      roleCount: 0
      cores: 2
      memory: 20
      diskSize: 50
      storageClass: host-nfs-storageclass
      baseImageVolumeName: openstack-base-img
      ctlplaneInterface: enp2s0 #defaults to enp2s0
      networks:
      - ctlplane
      - external
      - internalapi
      - tenant
      - storage
      - storagemgmt
    somecustomrole:
      roleName: SomeCustomRole
      isTripleoRole: false
      roleCount: 0
      cores: 2
      memory: 20
      diskSize: 50
      storageClass: host-nfs-storageclass
      baseImageVolumeName: openstack-base-img
      ctlplaneInterface: enp2s0 #defaults to enp2s0
      networks:
      - ctlplane
      - external
      - internalapi
