apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackClient
metadata:
  name: openstackclient
  namespace: openstack
spec:
  imageURL: registry.redhat.io/rhosp-beta/openstack-tripleoclient:16.2
  deploymentSSHSecret: osp-controlplane-ssh-keys
  networks:
    - ctlplane
  storageClass: host-nfs-storageclass
