apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: overcloud
  namespace: openstack
spec:
  openStackClientImageURL: quay.io/openstack-k8s-operators/tripleo-deploy:latest
  ospNetwork:
    bridgeName: br-osp
    name: osp
    nodeNetworkConfigurationPolicy:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      desiredState:
        interfaces:
        - bridge:
            options:
              stp:
                enabled: false
            port:
            - name: enp6s0
          description: Linux bridge with enp6s0 as a port
          name: br-osp # must be same as bridgeName
          state: up
          type: linux-bridge
  virtualMachineRoles:
  - role: Controller
    roleCount: 0
    cores: 2
    memory: 20
    diskSize: 50
    baseImageURL: http://download.eng.brq.redhat.com/brewroot/packages/rhel-guest-image/8.3/417/images/rhel-guest-image-8.3-417.x86_64.qcow2
    storageClass: host-nfs-storageclass
    baseImageVolumeName: openstack-base-img #optional
    networks:
    - ctlplane

  - role: SomeCustomVM
    isTripleoRole: false
    roleCount: 0
    cores: 2
    memory: 20
    diskSize: 50
    baseImageURL: http://download.eng.brq.redhat.com/brewroot/packages/rhel-guest-image/8.3/417/images/rhel-guest-image-8.3-417.x86_64.qcow2
    storageClass: host-nfs-storageclass
    #baseImageVolumeName: #optional
    networks:
    - ctlplane