apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackNet
metadata:
  name: storage
spec:
  allocationEnd: 172.18.0.250
  allocationStart: 172.18.0.10
  attachConfiguration: br-osp
  cidr: 172.18.0.0/24
  mtu: 1350
  name: Storage
  nameLower: storage
  vip: true
  vlan: 30
