apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackVMSet
metadata:
  name: customvmset
  namespace: openstack
spec:
  baseImageURL: http://download.devel.redhat.com/brewroot/packages/rhel-guest-image/8.4/1168/images/rhel-guest-image-8.4-1168.x86_64.qcow2
  vmCount: 1
  cores: 2
  memory: 5
  diskSize: 10
  storageClass: host-nfs-storageclass
  #imageImportStorageClass: local #optional
  deploymentSSHSecret: osp-controlplane-ssh-keys
  isTripleoRole: true
  ctlplaneInterface: enp2s0 #defaults to enp2s0
  networks:
    - ctlplane
  roleName: SomeCustomRole
