name: OSP Director Operator image builder

on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - .pull_request_pipeline
      - changelog.txt
      - kuttl-test.yaml
      - LICENSE
      - Makefile
      - OWNERS
      - PROJECT
      - README.md
      - .github/
      - build/
      - docs/
      - tests/

jobs:
  build-osp-director-operator:
    name: Build osp-director-operator image using buildah
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Buildah Action
      id: build-osp-director-operator
      uses: redhat-actions/buildah-build@v2
      with:
        image: osp-director-operator
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Dockerfile

    - name: Push osp-director-operator To Quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-osp-director-operator.outputs.image }}
        tags: ${{ steps.build-osp-director-operator.outputs.tags }}
        registry: quay.io/openstack-k8s-operators
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

  build-osp-director-downloader:
    name: Build rhel-downloader image using buildah
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Buildah Action
      id: build-osp-director-downloader
      uses: redhat-actions/buildah-build@v2
      with:
        image: rhel-downloader
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./containers/image_downloader/Dockerfile
        build-args: |
          REMOTE_SOURCE=containers/image_downloader

    - name: Push rhel-downloader To Quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-osp-director-downloader.outputs.image }}
        tags: ${{ steps.build-osp-director-downloader.outputs.tags }}
        registry: quay.io/openstack-k8s-operators
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

  build-osp-director-provisioner:
    name: Build provision-ip-discovery-agent image using buildah
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Buildah Action
      id: build-osp-director-provisioner
      uses: redhat-actions/buildah-build@v2
      with:
        image: provision-ip-discovery-agent
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Dockerfile.provision-ip-discovery-agent

    - name: Push provision-ip-discovery-agent To Quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-osp-director-provisioner.outputs.image }}
        tags: ${{ steps.build-osp-director-provisioner.outputs.tags }}
        registry: quay.io/openstack-k8s-operators
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

  build-osp-director-operator-bundle:
    needs: [ build-osp-director-operator, build-osp-director-downloader, build-osp-director-provisioner ]
    name: osp-director-operator-bundle
    runs-on: ubuntu-latest

    steps:
    - name: Checkout osp-director-operator repository
      uses: actions/checkout@v2

    - name: Install operator-sdk
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        operator-sdk: 'latest'

    - name: Log in to Red Hat Registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Create bundle image
      run: |
        pushd "${GITHUB_WORKSPACE}"/.github/
        chmod +x "create_bundle.sh"
        "./create_bundle.sh"
        popd
      env:
        REGISTRY: quay.io/openstack-k8s-operators
        GITHUB_SHA: ${{ github.sha }}
        BASE_IMAGE: osp-director-operator

    - name: Build osp-director-operator-bundle using buildah
      id: build-osp-director-operator-bundle
      uses: redhat-actions/buildah-build@v2
      with:
        image: osp-director-operator-bundle
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./bundle.Dockerfile

    - name: Push osp-director-operator To Quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-osp-director-operator-bundle.outputs.image }}
        tags: ${{ steps.build-osp-director-operator-bundle.outputs.tags }}
        registry: quay.io/openstack-k8s-operators
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
