{{/* info on golang template at https://pkg.go.dev/text/template */}}
# Resource Registry
resource_registry:
  OS::TripleO::DeployedServer::ControlPlanePort: deployed-server/deployed-neutron-port.yaml
  OS::TripleO::Network::Ports::ControlPlaneVipPort: deployed-server/deployed-neutron-port.yaml
  OS::TripleO::Network::Ports::NetVipMap: network/ports/net_vip_map_external.yaml
  OS::TripleO::Network::Ports::RedisVipPort: network/ports/noop.yaml
  OS::TripleO::Network::Ports::OVNDBsVipPort: network/ports/noop.yaml
  OS::TripleO::Network::Ports::ExternalVipPort: network/ports/noop.yaml
  OS::TripleO::Network::Ports::InternalApiVipPort: network/ports/noop.yaml
  OS::TripleO::Network::Ports::StorageVipPort: network/ports/noop.yaml
  OS::TripleO::Network::Ports::StorageMgmtVipPort: network/ports/noop.yaml
  # for OSP16.2 set OVNMacAddressNetwork and OVNMacAddressPort to None, see https://github.com/openstack-k8s-operators/osp-director-operator/issues/254
  OS::TripleO::OVNMacAddressNetwork: OS::Heat::None
  OS::TripleO::OVNMacAddressPort: OS::Heat::None
{{- range $roleid, $role := .RolesMap }}
{{- if ne $role.Name "ControlPlane" }}
{{- range $netid, $net := $role.Networks }}
{{- if ne $net.NameLower "ctlplane" }}
  OS::TripleO::{{ $role.Name }}::Ports::{{ $net.Name }}Port: network/ports/{{ $net.NameLower }}_from_pool.yaml
{{- end }}
{{- end }}
{{- end }}
{{- end }}

# Parameter Defaults
parameter_defaults:
  StackAction: CREATE
  DeployIdentifier: DeployIdentifier
  SoftwareConfigTransport: POLL_SERVER_HEAT
  RootStackName: overcloud
  ManageNetworks: False
  #
  # DeployedServerPortMap
  DeployedServerPortMap:
{{- range $roleid, $role := .RolesMap }}
{{- range $nodeid, $node := $role.Nodes }}
{{- range $netname, $ip := $node.IPaddr }}
{{- if eq $netname "ctlplane" }}
{{- if $node.VIP }}
    control_virtual_ip:
{{- else }}
    {{ $node.Hostname }}-{{ $netname }}:
{{- end }}
      fixed_ips:
        - ip_address: {{ $ip.IPaddr }}
      subnets:
        - cidr: {{ $ip.Subnet }}
      network:
        tags:
          - {{ $ip.Subnet }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
  #
  # Per ctlplane details
{{- range $netid, $net := .NetworksMap }}
{{- if eq $net.Name "Control" }}
  ControlPlaneDefaultRoute: {{ $net.Gateway }}
  ControlPlaneSubnetCidr: {{ $net.CidrSuffix }}
{{- end }}
{{- end }}
  #
  #<NETNAME>NetworkVip
  {{- range $roleid, $role := .RolesMap }}
{{- range $nodeid, $node := $role.Nodes }}
{{- range $netname, $ip := $node.IPaddr }}
{{- if $node.VIP }}
{{- if eq $netname "ctlplane" }}
  ControlPlaneIP: {{ $ip.IPaddr }}
{{- else }}
  {{ with (index $.NetworksMap $netname) }}{{ .Name }}{{ end }}NetworkVip: {{ $ip.IPaddr }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
  #
  # HostnameFormat and RoleCount
{{- range $roleid, $role := .RolesMap }}
{{- if ne $role.Name "ControlPlane" }}
  {{ $role.Name }}HostnameFormat: "{{ $role.NameLower }}-%index%"
  {{- $roleCount := len $role.Nodes }}
  {{ $role.Name }}Count: {{ $roleCount }}
{{- end }}
{{- end }}
  #
  # HostnameMap
  HostnameMap:
{{- range $roleid, $role := .RolesMap }}
{{- range $nodeid, $node := $role.Nodes }}
{{- if and (not $node.VIP) }}
    {{ $role.NameLower }}-{{ $node.Index }}: {{ $node.Hostname }}
{{- end }}
{{- end }}
{{- end }}
  #
  # ips-from-pool
{{- range $roleid, $role := .RolesMap }}
{{- if ne $role.Name "ControlPlane" }}
  {{ $role.Name }}IPs:
{{- range $networkid, $network := $role.Networks }}
{{- if ne $network.NameLower "ctlplane" }}
      {{ $network.NameLower }}:
{{- range $nodeid, $node := $role.Nodes }}
{{- range $netname, $ip := $node.IPaddr }}
{{- if eq $ip.Subnet $network.Cidr }}
        - {{ $ip.IPaddr }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}